name: Python application

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Building wheels
      run: |
        python -m pip install --upgrade pip
        pip wheel .
        dir
        cd build
        dir
        cd ..
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: hnswlib-0.6.0-cp37-cp37m-win_amd64.whl
        asset_name: hnswlib-0.6.0-cp37-cp37m-win_amd64.whl
        tag: latest-wheels
        overwrite: true
        body: "This is my release text"
